import { StyleSheet } from 'react-native'

const recargas_dos_styles = StyleSheet.create({
  formContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 24,
    margin: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 5,
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#222',
    marginBottom: 24,
    textAlign: 'center',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#e1e1e1',
    borderRadius: 12,
    paddingHorizontal: 12,
    marginBottom: 15,
    height: 56,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 18,
    color: '#333',
    height: '100%',
  },
  clearButton: {
    padding: 6,
  },
  validationText: {
    color: '#e20613',
    fontSize: 13,
    marginBottom: 15,
  },
  button: {
    height: 56,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 8,
    flexDirection: 'row',
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  buttonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '600',
    marginRight: 6,
  },
  buttonTextDisabled: {
    color: '#888',
  },
  infoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 20,
    padding: 12,
    backgroundColor: '#f0f8ff',
    borderRadius: 10,
  },
  infoText: {
    marginLeft: 8,
    color: '#444',
    fontSize: 13,
    flexShrink: 1,
  },
  bottomBackground: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 150,
    backgroundColor: '#f0f5ff',
    zIndex: -1,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },

  //plan

  pagerView: {
    flex: 1,
  },
  page: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  plansContainer: {
    padding: 20,
    flex: 1,
  },
  plansTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#fff',
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    marginHorizontal: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
    width: '40%',
    textAlign: 'center',
    height: 420,
  },
  planImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 16,
    objectFit: 'fill',
  },
  planName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#222',
    textAlign: 'center',
    marginBottom: 8,
  },
  planPrice: {
    fontSize: 18,
    fontWeight: '600',
    color: '#0068d1',
    textAlign: 'center',
    marginBottom: 8,
  },
  planDetails: {
    fontSize: 14,
    color: '#444',
    marginBottom: 4,
    width: '100%',
    textAlign: 'center',
  },
  planTicket: {
    fontSize: 12,
    color: '#777',
    marginTop: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 12,
    marginBottom: 8,
  },
  buttonTicket: {
    backgroundColor: '#0068d1',
    padding: 8,
    borderRadius: 12,
    marginTop: 12,
  },
  buttonTxtTicket: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  verMasText: {
    color: '#0068d1',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 6,
  },
})

export default recargas_dos_styles
